import Calendar from '@/components/calendar'
import Navbar from '@/components/navbar'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-screen pt-12 bg-slate-50'>
        <Navbar />

        <Calendar />
        <div className='container max-w-7xl mx-auto h-full pt-12'>{children}</div>
      </body>
    </html>
  )
}
